version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: SpringDbBackend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"